swagger: "2.0"
info:
  title: Test Integration API
  version: "1.0.0"
host: api.test.com
basePath: /v1
schemes:
  - https

paths:
  /hello:
    get:
      operationId: sayHello
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
                nullable: true
