packages:
  - packages/*
  - apps/*
  - examples/*

catalog:
  '@tsconfig/node22': ^22.0.5
  '@types/node': ^22.16.2
  '@typescript/native-preview': ^7.0.0-dev.20260124.1
  '@vitest/coverage-v8': ^4.1.4
  embedme: ^1.22.1
  oxfmt: ^0.41.0
  tsup: ^8.5.1
  vite: ^7.3.2
  vitest: ^4.1.4

cleanupUnusedCatalogs: true

minimumReleaseAge: 5700

onlyBuiltDependencies:
  - esbuild

overrides:
  'postman-collection@4.5.0>@faker-js/faker': 6.3.1
  'json-schema-faker@0.5.8>json-schema-ref-parser': npm:@apidevtools/json-schema-ref-parser@15.2.2
  sucrase@3.35.0>glob: 13.0.6
  express@4.22.1>path-to-regexp: 8.4.2
  fast-xml-parser@>=4.1.3 <4.5.4: '>=4.5.4'
  flatted@<3.4.0: '>=3.4.1'
  lodash@<=4.17.23: '>=4.18.1'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  node-forge@<1.4.0: '>=1.4.0'
  path-to-regexp@<0.1.13: '>=0.1.13'
  path-to-regexp@>=8.0.0 <8.4.0: '>=8.4.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  qs@<6.14.1: '>=6.14.1'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  svgo@>=3.0.0 <3.3.3: '>=3.3.3'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  webpack-dev-server@<=5.2.0: '>=5.2.1'

packageImportMethod: clone-or-copy
