packages:
  - packages/*
  - apps/*

catalog:
  "@tsconfig/node22": ^22.0.2
  "@types/node": ^22.16.2
  prettier: 3.6.2
  tsup: ^8.5.0
  typescript: ~5.9.2
  "@vitest/coverage-v8": ^3.2.4
  embedme: ^1.22.1
  eslint: ^9.34.0
  vitest: ^3.2.4

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild
