packages:
  - packages/*
  - apps/*

catalog:
  '@tsconfig/node22': ^22.0.2
  '@types/node': ^22.16.2
  embedme: ^1.22.1
  eslint: ^9.34.0
  prettier: 3.6.2
  tsup: ^8.5.0
  typescript: ~5.9.2

cleanupUnusedCatalogs: true

minimumReleaseAge: 5700

onlyBuiltDependencies:
  - esbuild

overrides:
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  node-forge@*: '>=1.3.2'
  vite@*: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
  webpack-dev-server@<=5.2.0: '>=5.2.1'

packageImportMethod: clone-or-copy
