openapi: 3.1.0
info:
  title: Test API with Inline Request Schema
  version: 1.0.0
paths:
  /test-inline-request:
    post:
      operationId: testInlineRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: number
                email:
                  type: string
                  format: email
              required:
                - name
                - email
      responses:
        201:
          description: Created
  /test-ref-request:
    post:
      operationId: testRefRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: Created
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - name
        - email
