openapi: 3.1.0
info:
  title: Test API for Discriminated Union Responses
  version: 1.0.0
paths:
  /test-multi-content-types:
    post:
      operationId: testMultiContentTypes
      summary: Test operation with multiple content types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewModel'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/NewModel'
            application/vnd.custom+json:
              schema:
                $ref: '#/components/schemas/NewModel'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '204':
          description: No content
components:
  schemas:
    NewModel:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    ErrorModel:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message