openapi: 3.1.0
info:
  title: No Server Test API
  description: Test API with no servers defined.
  version: 1.0.0
paths:
  /test:
    get:
      operationId: getTest
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
