swagger: "2.0"
info:
  title: Swagger 2.0 Test API
  version: "1.0.0"
  description: A test API to verify Swagger 2.0 to OpenAPI 3.1 conversion
host: api.example.com
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/CreateUserRequest"
      responses:
        201:
          description: User created successfully
          schema:
            $ref: "#/definitions/User"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/Error"

  /users/{id}:
    get:
      summary: Get user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: User found
          schema:
            $ref: "#/definitions/User"
        404:
          description: User not found
          schema:
            $ref: "#/definitions/Error"

definitions:
  User:
    type: object
    required:
      - id
      - email
    properties:
      id:
        type: string
        description: Unique user identifier
      email:
        type: string
        format: email
        description: User's email address
      name:
        type: string
        description: User's full name
        x-nullable: true
      age:
        type: integer
        minimum: 0
        maximum: 150
        description: User's age
      isActive:
        type: boolean
        default: true
        description: Whether the user account is active

  CreateUserRequest:
    type: object
    required:
      - email
    properties:
      email:
        type: string
        format: email
      name:
        type: string
      age:
        type: integer
        minimum: 0
        maximum: 150

  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        description: Error code
      message:
        type: string
        description: Error message
      details:
        type: string
        description: Additional error details
