openapi: 3.0.3
info:
  title: User Schemas Example
  version: 1.0.0
paths: {}

components:
  schemas:
    NormalUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the user.
        name:
          type: string
          description: The name of the user.
      required:
        - id
        - name

    AdminUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the admin user.
        name:
          type: string
          description: The name of the admin user.
        secret:
          type: string
          description: The secret field available only to administrators.
      required:
        - id
        - name
        - secret

    UserAnyOf:
      anyOf:
        - $ref: "#/components/schemas/NormalUser"
        - $ref: "#/components/schemas/AdminUser"

    UserOneOf:
      oneOf:
        - $ref: "#/components/schemas/NormalUser"
        - $ref: "#/components/schemas/AdminUser"
