export function buildMockRuntimeModule() {
  return [
    'import * as z from "zod";',
    'import { zocker } from "zocker";',
    "import {",
    "  normalizeContentType,",
    "  type GeneratedOperationHandler,",
    "  type GeneratedRouteDefinition,",
    "  type ResponseMap,",
    '} from "./runtime.js";',
    "",
    "interface SelectedResponseVariant {",
    "  contentType: string;",
    "  schema: z.ZodType;",
    "}",
    "",
    "export function createMockOperationHandler<TRoute extends GeneratedRouteDefinition>(",
    "  route: TRoute,",
    "): GeneratedOperationHandler<TRoute> {",
    "  return async (_input, _context) => {",
    "    const selectedStatus = selectStatus(route.responseMap);",
    "    if (selectedStatus === undefined) {",
    "      return {",
    '        status: "204",',
    '        contentType: "text/plain",',
    "        data: null,",
    "      };",
    "    }",
    "",
    "    const statusResponseMap = route.responseMap[selectedStatus];",
    "    if (statusResponseMap === undefined) {",
    "      return {",
    '        status: "204",',
    '        contentType: "text/plain",',
    "        data: null,",
    "      };",
    "    }",
    "",
    "    const selectedResponse = selectResponseVariant(statusResponseMap);",
    "    if (selectedResponse === undefined) {",
    "      return {",
    '        status: "204",',
    '        contentType: "text/plain",',
    "        data: null,",
    "      };",
    "    }",
    "",
    "    return {",
    "      status: selectedStatus,",
    "      contentType: selectedResponse.contentType,",
    "      data: generateMockData(selectedResponse.schema, route.operationId),",
    "    };",
    "  };",
    "}",
    "",
    "function generateMockData(schema: z.ZodType, operationId: string) {",
    "  try {",
    "    return zocker(schema).setSeed(123).generate();",
    "  } catch (error) {",
    "    console.error(`Error generating mock for ${operationId}:`, error);",
    "    return { error: `Mock generation failed for ${operationId}` };",
    "  }",
    "}",
    "",
    "function selectResponseVariant(",
    "  statusResponseMap: Record<string, z.ZodType>,",
    "): SelectedResponseVariant | undefined {",
    "  const jsonVariant = findResponseVariant(statusResponseMap, (contentType) => {",
    '    return contentType === "application/json";',
    "  });",
    "  if (jsonVariant !== undefined) {",
    "    return jsonVariant;",
    "  }",
    "",
    "  const structuredJsonVariant = findResponseVariant(",
    "    statusResponseMap,",
    '    (contentType) => contentType.endsWith("+json"),',
    "  );",
    "  if (structuredJsonVariant !== undefined) {",
    "    return structuredJsonVariant;",
    "  }",
    "",
    "  const textVariant = findResponseVariant(statusResponseMap, (contentType) => {",
    '    return contentType.startsWith("text/");',
    "  });",
    "  if (textVariant !== undefined) {",
    "    return textVariant;",
    "  }",
    "",
    "  const firstEntry = Object.entries(statusResponseMap)[0];",
    "  if (firstEntry === undefined) {",
    "    return undefined;",
    "  }",
    "",
    "  const [contentType, schema] = firstEntry;",
    "  return {",
    "    contentType,",
    "    schema,",
    "  };",
    "}",
    "",
    "function findResponseVariant(",
    "  statusResponseMap: Record<string, z.ZodType>,",
    "  predicate: (contentType: string) => boolean,",
    "): SelectedResponseVariant | undefined {",
    "  for (const [contentType, schema] of Object.entries(statusResponseMap)) {",
    "    const normalizedContentType = normalizeContentType(contentType);",
    "",
    "    if (normalizedContentType !== undefined && predicate(normalizedContentType)) {",
    "      return {",
    "        contentType,",
    "        schema,",
    "      };",
    "    }",
    "  }",
    "",
    "  return undefined;",
    "}",
    "",
    "function selectStatus(responseMap: ResponseMap) {",
    "  const statusCodes = Object.keys(responseMap).filter((status) => {",
    '    return status !== "default";',
    "  });",
    "",
    '  const successCodes = statusCodes.filter((status) => status.startsWith("2"));',
    "  if (successCodes.length > 0) {",
    "    return successCodes[0];",
    "  }",
    "",
    '  const redirectCodes = statusCodes.filter((status) => status.startsWith("3"));',
    "  if (redirectCodes.length > 0) {",
    "    return redirectCodes[0];",
    "  }",
    "",
    "  if (statusCodes.length > 0) {",
    "    return statusCodes[0];",
    "  }",
    "",
    '  return responseMap.default === undefined ? undefined : "default";',
    "}",
    "",
  ].join("\n");
}
