export function buildRuntimeModule() {
  return [
    'import type { Context, MiddlewareHandler } from "hono";',
    'import * as z from "zod";',
    'import { zocker } from "zocker";',
    "",
    "export type RequestMap = Record<string, z.ZodType>;",
    "export type ResponseMap = Record<string, Record<string, z.ZodType>>;",
    "",
    "export interface MockRouteDefinition {",
    "  operationId: string;",
    "  params?: z.ZodType;",
    "  requestMap: RequestMap;",
    "  responseMap: ResponseMap;",
    "}",
    "",
    "export interface MockResponse {",
    "  status: number | string;",
    "  contentType?: string;",
    "  data?: unknown;",
    "}",
    "",
    "type Simplify<T> = { [K in keyof T]: T[K] } & {};",
    "type InferSchema<TSchema> = TSchema extends z.ZodType ? z.infer<TSchema> : never;",
    "type InferParams<TParams> = TParams extends z.ZodType ? z.infer<TParams> : {};",
    "type InferBodyData<TRequestMap extends RequestMap> = InferSchema<",
    "  TRequestMap[keyof TRequestMap]",
    ">;",
    "type ParamGroup = 'headers' | 'path' | 'query';",
    "type InferParamGroup<TParams, TKey extends ParamGroup> = TParams extends z.ZodType",
    "  ? z.infer<TParams> extends infer TParsedParams",
    "    ? TParsedParams extends Record<string, unknown>",
    "      ? TKey extends keyof TParsedParams",
    "        ? NonNullable<TParsedParams[TKey]>",
    "        : never",
    "      : never",
    "    : never",
    "  : never;",
    "type InferBody<TRequestMap extends RequestMap> = keyof TRequestMap extends never",
    "  ? {}",
    "  : {",
    "      body?: InferBodyData<TRequestMap>;",
    "      contentType?: string;",
    "    };",
    "type InferValidatedTargets<TRoute extends MockRouteDefinition> = Simplify<",
    "  (InferParamGroup<TRoute['params'], 'path'> extends never",
    "    ? {}",
    "    : { param: InferParamGroup<TRoute['params'], 'path'> }) &",
    "    (InferParamGroup<TRoute['params'], 'query'> extends never",
    "      ? {}",
    "      : { query: InferParamGroup<TRoute['params'], 'query'> }) &",
    "    (InferParamGroup<TRoute['params'], 'headers'> extends never",
    "      ? {}",
    "      : { header: InferParamGroup<TRoute['params'], 'headers'> }) &",
    "    (keyof TRoute['requestMap'] extends never",
    "      ? {}",
    "      : {",
    "          form: InferBodyData<TRoute['requestMap']>;",
    "          json: InferBodyData<TRoute['requestMap']>;",
    "        })",
    ">;",
    "",
    "type ValidationResult =",
    "  | { success: true }",
    "  | {",
    "      error: unknown;",
    "      success: false;",
    "    };",
    "",
    "export type GeneratedOperationInput<TRoute extends MockRouteDefinition> = Simplify<",
    "  InferParams<TRoute['params']> & InferBody<TRoute['requestMap']>",
    ">;",
    "",
    "export type GeneratedOperationContext<TRoute extends MockRouteDefinition> = Context<",
    "  any,",
    "  string,",
    "  { out: InferValidatedTargets<TRoute> }",
    ">;",
    "export type GeneratedBodyContext<TBody> = Context<",
    "  any,",
    "  string,",
    "  {",
    "    out: {",
    "      form: TBody;",
    "      json: TBody;",
    "    };",
    "  }",
    ">;",
    "",
    "export function createMockUsecase<TRoute extends MockRouteDefinition>(route: TRoute) {",
    "  return async (_input: GeneratedOperationInput<TRoute>): Promise<MockResponse> => {",
    "    const selectedStatus = selectStatus(route.responseMap);",
    "    if (selectedStatus === undefined) {",
    "      return {",
    '        status: "204",',
    '        contentType: "text/plain",',
    "        data: null,",
    "      };",
    "    }",
    "",
    "    const statusResponseMap = route.responseMap[selectedStatus];",
    "    if (statusResponseMap === undefined) {",
    "      return {",
    '        status: "204",',
    '        contentType: "text/plain",',
    "        data: null,",
    "      };",
    "    }",
    "",
    "    const contentType = selectContentType(statusResponseMap);",
    "    const schema = statusResponseMap[contentType];",
    "    if (schema === undefined) {",
    "      return {",
    '        status: "204",',
    '        contentType: "text/plain",',
    "        data: null,",
    "      };",
    "    }",
    "",
    "    return {",
    "      status: selectedStatus,",
    "      contentType,",
    "      data: generateMockData(schema, route.operationId),",
    "    };",
    "  };",
    "}",
    "",
    "export function createValidationHook(route: MockRouteDefinition) {",
    "  return (result: ValidationResult, _context: Context) => {",
    "    if (result.success) {",
    "      return undefined;",
    "    }",
    "",
    "    return sendRouteResponse(createValidationErrorResponse(route, result.error));",
    "  };",
    "}",
    "",
    "export function createParamValidationOptions(",
    "  paramNameMap: Record<string, string>,",
    ") {",
    "  return {",
    "    validationFunction: async (",
    "      schema: z.ZodType,",
    "      value: Record<string, string | undefined>,",
    "    ) => {",
    "      return await schema.safeParseAsync(remapPathParams(value, paramNameMap));",
    "    },",
    "  };",
    "}",
    "",
    "export function createConditionalValidator(",
    "  expectedContentType: string,",
    "  validator: MiddlewareHandler,",
    "  route: MockRouteDefinition,",
    "): MiddlewareHandler {",
    "  return async (context, next) => {",
    '    const contentType = normalizeContentType(context.req.header("content-type"));',
    "",
    "    if (contentType !== expectedContentType) {",
    "      return await next();",
    "    }",
    "",
    "    try {",
    "      return await validator(context, next);",
    "    } catch (error) {",
    "      if (isBadRequestError(error)) {",
    "        return sendRouteResponse(",
    "          createValidationErrorResponse(route, error.message),",
    "        );",
    "      }",
    "",
    "      throw error;",
    "    }",
    "  };",
    "}",
    "",
    "export function createUnsupportedContentTypeMiddleware(",
    "  requestMap: RequestMap,",
    "  route: MockRouteDefinition,",
    "): MiddlewareHandler {",
    "  return async (context, next) => {",
    '    const contentType = normalizeContentType(context.req.header("content-type"));',
    "",
    "    if (contentType === undefined || Object.keys(requestMap).length === 0) {",
    "      return await next();",
    "    }",
    "",
    "    if (requestMap[contentType] !== undefined && isSupportedRequestBodyContentType(contentType)) {",
    "      return await next();",
    "    }",
    "",
    "    return sendRouteResponse(",
    "      createValidationErrorResponse(",
    "        route,",
    "        `Unsupported Content-Type: ${contentType}`,",
    "      ),",
    "    );",
    "  };",
    "}",
    "",
    "export function normalizeContentType(contentType?: string) {",
    '  return contentType?.split(";")[0]?.trim().toLowerCase();',
    "}",
    "",
    "export function readValidatedRequestBody<TBody>(",
    "  context: GeneratedBodyContext<TBody>,",
    "  contentType?: string,",
    ") {",
    "  if (contentType === undefined) {",
    "    return undefined;",
    "  }",
    "",
    "  if (isJsonContentType(contentType)) {",
    '    return context.req.valid("json");',
    "  }",
    "",
    "  if (isFormContentType(contentType)) {",
    '    return context.req.valid("form");',
    "  }",
    "",
    "  return undefined;",
    "}",
    "",
    "export function sendRouteResponse(result: MockResponse) {",
    "  const status = toHttpStatus(result.status);",
    "  const headers = new Headers();",
    "",
    "  if (result.contentType !== undefined) {",
    '    headers.set("content-type", result.contentType);',
    "  }",
    "",
    "  if (result.data === undefined || result.data === null) {",
    "    return new Response(null, { headers, status });",
    "  }",
    "",
    '  if (typeof result.data === "string") {',
    "    return new Response(result.data, { headers, status });",
    "  }",
    "",
    '  const contentType = result.contentType ?? "application/json";',
    '  headers.set("content-type", contentType);',
    "",
    "  return new Response(serializeResponseData(result.data), { headers, status });",
    "}",
    "",
    "export function createValidationErrorResponse(",
    "  route: MockRouteDefinition,",
    "  error: unknown,",
    "): MockResponse {",
    '  const badRequestResponse = route.responseMap["400"];',
    "",
    "  if (badRequestResponse !== undefined) {",
    "    const contentType = selectContentType(badRequestResponse);",
    "    const schema = badRequestResponse[contentType];",
    "",
    "    if (schema !== undefined) {",
    "      const mockData = generateMockData(schema, route.operationId);",
    "",
    "      return {",
    '        status: "400",',
    "        contentType,",
    "        data: {",
    "          ...(isRecord(mockData) ? mockData : { mockData }),",
    "          details: error,",
    "          message: prettifyValidationError(error),",
    "        },",
    "      };",
    "    }",
    "  }",
    "",
    "  return {",
    '    status: "400",',
    '    contentType: "application/json",',
    "    data: {",
    '      error: "Bad Request",',
    "      details: error,",
    "      message: prettifyValidationError(error),",
    "    },",
    "  };",
    "}",
    "",
    "function remapPathParams(",
    "  rawParams: Record<string, string | undefined>,",
    "  paramNameMap: Record<string, string>,",
    ") {",
    "  return Object.fromEntries(",
    "    Object.entries(paramNameMap).map(([original, sanitized]) => {",
    "      return [original, rawParams[sanitized]];",
    "    }),",
    "  );",
    "}",
    "",
    "function isSupportedRequestBodyContentType(contentType: string) {",
    "  return isJsonContentType(contentType) || isFormContentType(contentType);",
    "}",
    "",
    "function isJsonContentType(contentType: string) {",
    '  return contentType === "application/json" || contentType.endsWith("+json");',
    "}",
    "",
    "function isFormContentType(contentType: string) {",
    "  return (",
    '    contentType === "application/x-www-form-urlencoded" ||',
    '    contentType === "multipart/form-data"',
    "  );",
    "}",
    "",
    "function generateMockData(schema: z.ZodType, operationId: string) {",
    "  try {",
    "    return zocker(schema).setSeed(123).generate();",
    "  } catch (error) {",
    "    console.error(`Error generating mock for ${operationId}:`, error);",
    "    return { error: `Mock generation failed for ${operationId}` };",
    "  }",
    "}",
    "",
    "function hasIssues(value: unknown): value is {",
    "  issues: Array<{ message: string; path?: PropertyKey[] }>;",
    "} {",
    "  return (",
    '    typeof value === "object" &&',
    "    value !== null &&",
    '    "issues" in value &&',
    "    Array.isArray(value.issues)",
    "  );",
    "}",
    "",
    "function isBadRequestError(error: unknown): error is {",
    "  message: string;",
    "  status: 400;",
    "} {",
    '  return isRecord(error) && error.status === 400 && typeof error.message === "string";',
    "}",
    "",
    "function isRecord(value: unknown): value is Record<string, unknown> {",
    '  return typeof value === "object" && value !== null;',
    "}",
    "",
    "function prettifyValidationError(error: unknown) {",
    "  if (hasIssues(error)) {",
    "    return error.issues",
    "      .map((issue) => {",
    "        const path =",
    "          issue.path !== undefined && issue.path.length > 0",
    '            ? issue.path.join(".")',
    '            : "root";',
    "",
    "        return `${path}: ${issue.message}`;",
    "      })",
    '      .join("; ");',
    "  }",
    "",
    "  if (error instanceof Error) {",
    "    return error.message;",
    "  }",
    "",
    '  if (typeof error === "string") {',
    "    return error;",
    "  }",
    "",
    '  return "Invalid request parameters";',
    "}",
    "",
    "function selectContentType(statusResponseMap: Record<string, z.ZodType>) {",
    '  return statusResponseMap["application/json"] !== undefined',
    '    ? "application/json"',
    '    : (Object.keys(statusResponseMap)[0] ?? "application/json");',
    "}",
    "",
    "function selectStatus(responseMap: ResponseMap) {",
    "  const statusCodes = Object.keys(responseMap).filter((status) => {",
    '    return status !== "default";',
    "  });",
    "",
    '  const successCodes = statusCodes.filter((status) => status.startsWith("2"));',
    "  if (successCodes.length > 0) {",
    "    return successCodes[0];",
    "  }",
    "",
    '  const redirectCodes = statusCodes.filter((status) => status.startsWith("3"));',
    "  if (redirectCodes.length > 0) {",
    "    return redirectCodes[0];",
    "  }",
    "",
    "  if (statusCodes.length > 0) {",
    "    return statusCodes[0];",
    "  }",
    "",
    '  return responseMap.default === undefined ? undefined : "default";',
    "}",
    "",
    "function serializeResponseData(data: unknown) {",
    "  return JSON.stringify(data, (_, value: unknown) => {",
    '    return typeof value === "bigint" ? value.toString() : value;',
    "  });",
    "}",
    "",
    "function toHttpStatus(status: number | string) {",
    '  if (typeof status === "number") {',
    "    return Number.isFinite(status) ? status : 500;",
    "  }",
    "",
    '  if (status === "default") {',
    "    return 500;",
    "  }",
    "",
    "  const parsedStatus = Number.parseInt(status, 10);",
    "  return Number.isNaN(parsedStatus) ? 500 : parsedStatus;",
    "}",
    "",
  ].join("\n");
}
