name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Generate integration test client
        run: pnpm start generate -i tests/integrations/fixtures/test.yaml -o tests/integrations/generated --generate-client --generate-server

      - name: Run format check
        run: pnpm format:check

      - name: Run lint check
        run: pnpm lint:check

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test
